= KotlinMultiplatformStripe
:toc:
:source-highlighter: highlightjs

== Introduction

A basic WORK IN PROGRESS Kotlin Multiplatform + Compose Multiplatform implementation of the Stripe PaymentElement for Android, iOS, and wasmJs

Right now, only doing checkout on a PaymentIntent is supported. iOS requires manually linking the StripeIosBridge.xcframework (See iosApp) and wasmJs requires some changes in index.html and main.kt (See the demo app)

== Getting Started

. Integrate this library as a dependency in your project:
.. Add the Maven repository to your `settings.gradle`
... `maven("https://k1ra.net/nexus/repository/public")`
.. Add the dependency:
... `implementation("net.k1ra.kotlinmultiplatformstripe:KotlinMultiplatformStripe:latest.release")`

== Usage Examples

There are usage examples in the KotlinMultiplatformStripeDemo app in this project


== Environment Setup

* Since this is a KMM project, a modern version of Android Studio (2023.1.1 or newer) is required
* Remember to configure Android Studio to use Java 17

== Dokka
https://k1rak1ra.github.io/KotlinMultiplatformStripe/index.html

== Conduct

This is a professional environment, and you are expected to conduct yourself in a professional and courteous manner.
If you fail to exhibit appropriate conduct, your contributions and interactions will no longer be welcome here.

== Contributing

* Everyone is welcome and encouraged to contribute.
If you are looking for a place to start, try working on an unassigned issue with the `good-first-issue` tag.
* All contributions are expected to conform to standard Kotlin code style and be covered by unit tests.
* PRs will not be merged if there are failing tests.
* If you would like to contribute code you can do so through GitHub by forking the repository and sending a pull request.
* When submitting code, please follow the existing conventions and style in order to keep the code readable.
